apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ejemplo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/DanielVerano/argocd-ejemplo
    path: manifests
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true